# Generated by Django 4.0.4 on 2022-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatoo', '0002_alter_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
